run:
  skip-dirs:
    - ent/*

linters:
  enable-all: true
  disable:
    # Deprecated
    - deadcode
    - golint
    - exhaustivestruct
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - structcheck
    - scopelint
    - varcheck

    # Error `interface {} is nil, not *buildssa.SSA`
    - bodyclose
    - contextcheck
    - nilerr
    - rowserrcheck
    - unparam

    # Error `ent.withHooks$1: cannot convert *t0 (M) to PM`
    - noctx
    - sqlclosecheck
    - tparallel
    - wastedassign
